Algoritmo "areaquadrado"
// 
//  
// Descrição   : algoritmo pede ao usuario para digitar os lados de um quadrado e retorna o sucessor dele;
// Autor(a)    : Gabriel de Oliveira
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis 
lado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe o lado do seu quadrado: ")
leia(lado)
escreva(" A área do seu quadrado é: ", lado*lado)

Fimalgoritmo