Algoritmo "areacirculo"
// 
//  
// Descrição   : algoritmo pede ao usuario para digitar raio de um ciruclo e retorna a área dele;
// Autor(a)    : Gabriel de Oliveira
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis 
 raio:real             //A = p. r²
 p:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Escreva o raio do seu ciruclo: ")
leia(raio)
escreva("A área do seu circulo é: ", pi*(raio*raio))

Fimalgoritmo