Algoritmo "Numero antecessor"
// 
//  
// Descrição   : Algoritmo que pede ao usuario um numero e retorna o antecessor dele
// Autor(a)    : Gabriel de Oliveira
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis 
valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe um número: ")
leia(valor)
escreva("O antecessor de: ", valor , " é: " , valor -1)

Fimalgoritmo