Algoritmo "sucessor"
// 
//  
// Descrição   : algoritmo pede ao usuario para digitar um numero e retorna o sucessor dele;
// Autor(a)    : Gabriel de Oliveira
// Data atual  : 29/08/2024
Var
// Seção de Declarações das variáveis 
 valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Escreva um número: ")
leia(valor)
escreva("O sucessor de: ", valor, " é: ", valor+1)

Fimalgoritmo